### ISSUE TITLE
hello,is there Sample of watermarks employed in this paper ?

### ISSUE THREAD

**Issue by xiaolinjieer** [dingsheng-ong/ipr-gan#1]

**Comment by RorschachChen** [comment]
Actually no. But you can specify any pics as your watermark during training.

**Comment by RorschachChen** [comment]
> Actually no. But you can specify any pics as your watermark during training.

with option "-w watermark.png"

**Comment by dingsheng-ong** [comment]
Thanks for showing interest in our work.  I'm sorry that we will not providing the sample of watermarks provided in the paper. But, as mentioned by @RorschachChen, you can specify any image with the option "`-wm watermark.png`".
