### ISSUE TITLE
When learning about the training process of cyclegan, I found that during training, the size of the picture is 128 * 128, and the watermark size is 64, accounting for one quarter. During evaluation, the size of the picture becomes 256 * 256, and the watermark size is still 64, accounting for one eighth. Is this phenomenon intentional or is there a problem with my setting?

### ISSUE THREAD

**Issue by a1340080222** [dingsheng-ong/ipr-gan#7]
When learning about the training process of cyclegan, I found that during training, the size of the picture is 128 * 128, and the watermark size is 64, accounting for one quarter. During evaluation, the size of the picture becomes 256 * 256, and the watermark size is still 64, accounting for one eighth. Is this phenomenon intentional or is there a problem with my setting?

**Comment by dingsheng-ong** [comment]
Yes, this is the expected behaviour. Thanks for pointing that out!
